version: '3.7'
services:
  phpunit:
    build:
      context: .
    volumes:
      - ./reports:/usr/src/reports
      - ./src:/usr/src/src
      - ./tests:/usr/src/tests
      - ./phpunit.xml:/usr/src/phpunit.xml
      - ./composer.json:/usr/src/composer.json
      - ./composer.lock:/usr/src/composer.lock
  sonar:
    image: sonarsource/sonar-scanner-cli
    volumes:
      - ./:/usr/src
    env:
      - SONAR_HOST_URL=https://sonarcloud.io
      - SONAR_TOKEN=${SONAR_TOKEN}
