version: '3.7'
services:
  phpunit:
    build:
      context: .
    volumes:
    - ./reports:/tmp/reports
    - ./src:/tmp/src
    - ./tests:/tmp/tests
    - ./phpunit.xml:/tmp/phpunit.xml
    - ./composer.json:/tmp/composer.json
    - ./composer.lock:/tmp/composer.lock
