name: ci-for-prs
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run unit tests
        run:  docker-compose run --rm phpunit
      - name: create sonar directorie with correct file permissions
        run: mkdir .sonar .sonar/cache .scannerwork && sudo chmod -R 777 .sonar && sudo chmod -R 777 .scannerwork
      - name: SonarCloud Scan
        run:  sonar-scanner -Dsonar.pullrequest.branch=${{ github.head_ref }} -Dsonar.pullrequest.key=${{ github.event.number }} -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          SONAR_HOST_URL: 'https://sonarcloud.io'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
          CHECK_PLATFORM_REQUIREMENTS: false
        with:
          args: analyse -c phpstan.neon
  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run psalm
        run:  docker-compose run --rm psalm
