on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Composer packages dependencies
        uses: MilesChou/composer-action/7.1/install@master
        with:
          args: install --no-progress --ignore-platform-reqs
      - name: phpunit with ext xdebug enabled
        uses: MilesChou/docker-xdebug/7.1/@master
        with:
          args: phpunit
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
