on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: run unit tests
        run:  docker-compose run --rm phpunit
      - name: create sonar directorie with correct file permissions
        run: mkdir .sonar .sonar/cache .scannerwork && sudo chmod -R 777 .sonar && sudo chmod -R 777 .scannerwork
      - name: SonarCloud Scan
        run:  docker-compose run --rm sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_BRANCH_NAME: ${GITHUB_REF##*/}
          SONAR_PULLREQUEST_PROVIDER: "github"
          SONAR_PULLREQUEST_GITHUB_REPOSITORY: ${{ github.repository }}
          SONAR_PULLREQUEST_KEY: ${{ github.event.number }}
          SONAR_PULLREQUEST_BASE: ${{ github.base_ref }}
