on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  unit-test-and-sonar-for-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: run unit tests
        run:  docker-compose run --rm phpunit
      - name: create sonar directorie with correct file permissions
        run: mkdir .sonar .sonar/cache .scannerwork && sudo chmod -R 777 .sonar && sudo chmod -R 777 .scannerwork
      - name: SonarCloud Scan
        run:  docker-compose run --rm sonar
        env:
          SONAR_HOST_URL: 'https://sonarcloud.io'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PULLREQUEST_BRANCH: ${{ github.head_ref }}
          SONAR_PULLREQUEST_KEY: ${{ github.event.number }}
          SONAR_PULLREQUEST_BASE: ${{ github.base_ref }}
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
        with:
          args: analyse -c phpstan.neon
