on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Composer packages dependencies
        uses: docker://composer:1.9.1
        with:
          args: install --no-progress --ignore-platform-reqs
      - name: PHPUnit testing
        uses: docker://phpunit:latest
        with:
          args: -c phpunit.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
